### ISSUE TITLE
3D Deep Learning in Function Space - GTC Slides are missing

### ISSUE THREAD

**Issue by rayryeng** [m-niemeyer/m-niemeyer.github.io#1]
Hello!

Thanks for posting all of your content on 3D Deep Learning. It's especially useful for a newcomer to this field such as myself. I remember accessing your slides on your talk on 3D Deep learning in Function Space from the NVIDIA GTC conference a while ago - https://m-niemeyer.github.io/slides/gtc/. Now when I visit this URL, it says the slides can't be found. Is this intentional? If not, may I ask where I can get a copy or could you correct the URL on your website to point to where they are?  Thanks!

**Comment by m-niemeyer** [comment]
Hi,

thanks for your nice words and thanks for spotting this - should be back up now!

Best,
Michael
